-- create table admin(
--     id INT NOT NULL,
--     username Varchar2(40),
--     Email varchar2(40),
--     mobile varchar2(11),
--     password varchar2(255),
--     CONSTRAINT ADMIN_PK PRIMARY KEY (ID)
-- );

-- CREATE SEQUENCE admin_seq START WITH 1;

-- CREATE OR REPLACE TRIGGER ADMIN_ID
-- BEFORE INSERT ON admin
-- FOR EACH ROW

-- BEGIN
--   SELECT admin_seq.NEXTVAL
--   INTO   :new.id
--   FROM   dual;
-- END;
-- /

create table users(
    id INT NOT NULL,
    username Varchar2(40),
    Email varchar2(40),
    mobile varchar2(11),
    dob DATE,
    password varchar2(255),
    isAdmin NUMBER(1,0) DEFAULT 0,
    CONSTRAINT user_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE users_seq START WITH 1;

CREATE OR REPLACE TRIGGER user_ID
BEFORE INSERT ON users
FOR EACH ROW

BEGIN
  SELECT users_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/




CREATE TABLE TRAINS(
  TID INT,
  TNAME VARCHAR2(20),
  TOTAL_SEATS NUMBER(3,0),
  TOTAL_BLOCKS NUMBER(2,0),
  CONSTRAINT TRAIN_PK PRIMARY KEY (TID)
);

CREATE SEQUENCE TRAINS_seq START WITH 1000;

CREATE OR REPLACE TRIGGER TRAIN_ID
BEFORE INSERT ON TRAINS
FOR EACH ROW

BEGIN
  SELECT TRAINS_seq.NEXTVAL
  INTO   :new.TID
  FROM   dual;
END;
/

CREATE TABLE BLOCKS(
  BID INT,
  TID INT,
  B_NAME VARCHAR2(20),
  TOTAL_STEATS NUMBER(3,0),
  CLASS VARCHAR2(20),
  CONSTRAINT BLOCK_PK PRIMARY KEY (BID),
  CONSTRAINT BT_FK FOREIGN KEY (TID) REFERENCES TRAINS(TID)
);

CREATE SEQUENCE BLOCKS_seq START WITH 1;

CREATE OR REPLACE TRIGGER BLOCK_ID
BEFORE INSERT ON BLOCKS
FOR EACH ROW

BEGIN
  SELECT BLOCKS_seq.NEXTVAL
  INTO   :new.BID
  FROM   dual;
END;
/

CREATE TABLE SEATS(
  SID INT,
  SEAT_NUM INT,
  TID INT,
  BID INT,
  IS_BOOKED NUMBER(1,0),
  CONSTRAINT SPK PRIMARY KEY (SID),
  CONSTRAINT STD FOREIGN KEY REFERENCES TRAINS(TID),
  CONSTRAINT SBD FOREIGN KEY REFERENCES BLOCKS(BID)
);

CREATE SEQUENCE SEATS_seq START WITH 1;

CREATE OR REPLACE TRIGGER SEAT_ID
BEFORE INSERT ON SEATS
FOR EACH ROW

BEGIN
  SELECT SEATS_seq.NEXTVAL
  INTO   :new.SID
  FROM   dual;
END;
/


